# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['Spiel.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('bg1.png', '.'),
        ('BG_6.png', '.'),
        ('Lieferengpass.png', '.'),
        ('Flag.png', '.'),
        ('tariff_light_red.png', '.'),
        ('tariff_dark_red.png', '.'),
        ('tariff_orange.png', '.'),
        ('trump_1.png', '.'),
        ('trump_2.png', '.'),
        ('trump_3.png', '.'),
        ('player_idle.png', '.'),
        ('Player_walking_R_1.png', '.'),
        ('Player_walking_R_2.png', '.'),
        ('Player_walking_R_3.png', '.'),
        ('Player_walking_R_4.png', '.'),
        ('Player_walking_R_5.png', '.'),
        ('Player_walking_R_6.png', '.'),
        ('Player_walking_L_1.png', '.'),
        ('Player_walking_L_2.png', '.'),
        ('Player_walking_L_3.png', '.'),
        ('Player_walking_L_4.png', '.'),
        ('Player_walking_L_5.png', '.'),
        ('Player_walking_L_6.png', '.'),
        ('player_dead.png', '.'),
        ('crate_1.png', '.'),
        ('crate_2.png', '.'),
        ('crate_3.png', '.'),
        ('cutscene_trade_down.png', '.'),
        ('cutscene_trump.png', '.'),
        ('cutscene_scroll.png', '.'),
        ('cutscene_company.png', '.'),
        ('cutscene_deutschland.png', '.'),
        ('cutscene_boss_2.png', '.'),
        ('cutscene_ziel.png', '.'),
        ('keyboard_colored_1.png', '.'),
        ('keyboard_colored.png', '.'),
        ('money.png', '.'),
        ('pdf-sample_0.pdf', '.'),
        ('pdf-sample_1.pdf', '.'),
        ('highscores.json', '.'),
    ],
    hiddenimports=['pygame'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Spiel',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)